/**
 * Dados mock para visualização hierárquica de categorias
 * Estrutura: Família (Level 1) → Grupo (Level 2) → Subgrupo (Level 3)
 *
 * @deprecated Este arquivo contém dados mockados e não é mais utilizado.
 * Os dados reais agora são obtidos da API através do TaxonomyServiceApi.
 *
 * Este arquivo foi mantido para referência histórica, mas pode ser removido
 * em uma versão futura do sistema.
 */

import type { CategoryNode } from "./category-tree.types";

export const CATEGORY_TREE_DATA: CategoryNode[] = [
  {
    id: 825,
    name: "ELETRÔNICOS",
    slug: "eletronicos",
    level: 1,
    parentId: null,
    quantity: 45,
    children: [
      {
        id: 826,
        name: "Computadores",
        slug: "computadores",
        level: 2,
        parentId: 825,
        quantity: 12,
        children: [
          {
            id: 8261,
            name: "Notebooks",
            slug: "notebooks",
            level: 3,
            parentId: 826,
            quantity: 5,
          },
          {
            id: 8262,
            name: "Desktops",
            slug: "desktops",
            level: 3,
            parentId: 826,
            quantity: 4,
          },
          {
            id: 8263,
            name: "Tablets",
            slug: "tablets",
            level: 3,
            parentId: 826,
            quantity: 3,
          },
        ],
      },
      {
        id: 827,
        name: "Periféricos",
        slug: "perifericos",
        level: 2,
        parentId: 825,
        quantity: 18,
        children: [
          {
            id: 8271,
            name: "Mouses",
            slug: "mouses",
            level: 3,
            parentId: 827,
            quantity: 6,
          },
          {
            id: 8272,
            name: "Teclados",
            slug: "teclados",
            level: 3,
            parentId: 827,
            quantity: 7,
          },
          {
            id: 8273,
            name: "Monitores",
            slug: "monitores",
            level: 3,
            parentId: 827,
            quantity: 5,
          },
        ],
      },
      {
        id: 828,
        name: "Acessórios",
        slug: "acessorios",
        level: 2,
        parentId: 825,
        quantity: 15,
        children: [
          {
            id: 8281,
            name: "Cabos",
            slug: "cabos",
            level: 3,
            parentId: 828,
            quantity: 5,
          },
          {
            id: 8282,
            name: "Adaptadores",
            slug: "adaptadores",
            level: 3,
            parentId: 828,
            quantity: 5,
          },
          {
            id: 8283,
            name: "Carregadores",
            slug: "carregadores",
            level: 3,
            parentId: 828,
            quantity: 5,
          },
        ],
      },
    ],
  },
  {
    id: 829,
    name: "INFORMÁTICA",
    slug: "informatica",
    level: 1,
    parentId: null,
    quantity: 28,
    children: [
      {
        id: 8291,
        name: "Componentes",
        slug: "componentes",
        level: 2,
        parentId: 829,
        quantity: 12,
        children: [
          {
            id: 82911,
            name: "Processadores",
            slug: "processadores",
            level: 3,
            parentId: 8291,
            quantity: 4,
          },
          {
            id: 82912,
            name: "Memória RAM",
            slug: "memoria-ram",
            level: 3,
            parentId: 8291,
            quantity: 4,
          },
          {
            id: 82913,
            name: "Placas de Vídeo",
            slug: "placas-video",
            level: 3,
            parentId: 8291,
            quantity: 4,
          },
        ],
      },
      {
        id: 8292,
        name: "Software",
        slug: "software",
        level: 2,
        parentId: 829,
        quantity: 10,
        children: [
          {
            id: 82921,
            name: "Sistemas Operacionais",
            slug: "sistemas-operacionais",
            level: 3,
            parentId: 8292,
            quantity: 3,
          },
          {
            id: 82922,
            name: "Aplicativos",
            slug: "aplicativos",
            level: 3,
            parentId: 8292,
            quantity: 4,
          },
          {
            id: 82923,
            name: "Utilitários",
            slug: "utilitarios",
            level: 3,
            parentId: 8292,
            quantity: 3,
          },
        ],
      },
      {
        id: 8293,
        name: "Serviços",
        slug: "servicos",
        level: 2,
        parentId: 829,
        quantity: 6,
        children: [
          {
            id: 82931,
            name: "Suporte Técnico",
            slug: "suporte-tecnico",
            level: 3,
            parentId: 8293,
            quantity: 3,
          },
          {
            id: 82932,
            name: "Consultoria",
            slug: "consultoria",
            level: 3,
            parentId: 8293,
            quantity: 3,
          },
        ],
      },
    ],
  },
  {
    id: 830,
    name: "PERFUMES",
    slug: "perfumes",
    level: 1,
    parentId: null,
    quantity: 22,
    children: [
      {
        id: 8301,
        name: "Masculinos",
        slug: "perfumes-masculinos",
        level: 2,
        parentId: 830,
        quantity: 8,
        children: [
          {
            id: 83011,
            name: "Eau de Toilette",
            slug: "eau-de-toilette-m",
            level: 3,
            parentId: 8301,
            quantity: 4,
          },
          {
            id: 83012,
            name: "Eau de Parfum",
            slug: "eau-de-parfum-m",
            level: 3,
            parentId: 8301,
            quantity: 4,
          },
        ],
      },
      {
        id: 8302,
        name: "Femininos",
        slug: "perfumes-femininos",
        level: 2,
        parentId: 830,
        quantity: 8,
        children: [
          {
            id: 83021,
            name: "Eau de Toilette",
            slug: "eau-de-toilette-f",
            level: 3,
            parentId: 8302,
            quantity: 4,
          },
          {
            id: 83022,
            name: "Eau de Parfum",
            slug: "eau-de-parfum-f",
            level: 3,
            parentId: 8302,
            quantity: 4,
          },
        ],
      },
      {
        id: 8303,
        name: "Unissex",
        slug: "perfumes-unissex",
        level: 2,
        parentId: 830,
        quantity: 6,
        children: [
          {
            id: 83031,
            name: "Fragrâncias Neutras",
            slug: "fragrancias-neutras",
            level: 3,
            parentId: 8303,
            quantity: 3,
          },
          {
            id: 83032,
            name: "Fragrâncias Especiais",
            slug: "fragrancias-especiais",
            level: 3,
            parentId: 8303,
            quantity: 3,
          },
        ],
      },
    ],
  },
];
